.TH MS2DURATION "1" "2021" "INFO MONO" "User Commands"
.SH NAME
MS2DURATION \- Milliseconds to duration converter
.SH SYNOPSIS
.B ms2duration MILLISECONDS
.SH DESCRIPTION
MS2DURATION is a tool to convert milliseconds to full durations represent a length of time.
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/ms2duration/issues
